In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd /content/drive/MyDrive/Notability/UChicago_Q2_Winter_2022/PPHA Data visualization/DV_FP/

/content/drive/MyDrive/Notability/UChicago_Q2_Winter_2022/PPHA Data visualization/DV_FP

In [4]:
BASE_PATH = "/content/drive/MyDrive/Notability/UChicago_Q2_Winter_2022/PPHA Data visualization/DV_FP/"

In [5]:
summary = pd.read_csv(filepath_or_buffer = BASE_PATH + 'DV_FP_data_summary.csv')
summary

,"Region, subregion, country or area *",Country code,Parent code,1950-1955 pop,2015-2020 pop
0,Burundi,108,910,2 403,11 012
1,Comoros,174,910,166,823
2,Djibouti,262,910,65,951
3,Eritrea,232,910,851,3 438
4,Ethiopia,231,910,18 832,107 851
...,...,...,...,...,...
258,Bermuda,60,918,39,63
259,Canada,124,918,14 468,36 895
260,Greenland,304,918,24,57
261,Saint Pierre and Miquelon,666,918,5,6
262,United States of America,840,918,163 518,326 024

In [6]:
fert_mort= pd.read_csv(filepath_or_buffer = BASE_PATH + 'DV_FP_data _FERT_MORT.csv')
fert_mort.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country code    201 non-null    int64
 1   1950-1955 fert  201 non-null    float64
 2   2015-2020 fert  201 non-null    float64
 3   1950-1955 mort  201 non-null    int64
 4   2015-2020 mort  201 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 8.0 KB

In [7]:
df=fert_mort.merge(summary,on='Country code', how='left')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 0 to 200
Data columns (total 9 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Country code                          201 non-null    int64
 1   1950-1955 fert                        201 non-null    float64
 2   2015-2020 fert                        201 non-null    float64
 3   1950-1955 mort                        201 non-null    int64
 4   2015-2020 mort                        201 non-null    int64
 5   Region, subregion, country or area *  201 non-null    object
 6   Parent code                           201 non-null    int64
 7   1950-1955 pop                         201 non-null    object
 8   2015-2020 pop                         201 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 15.7+ KB

In [8]:
df['Parent code'].value_counts()

910     20
922     18
915     17
914     16
931     13
925     12
924     11
920     11
923     10
911      9
5501     9
916      8
906      8
912      7
926      7
928      5
5500     5
913      5
954      3
957      3
927      2
918      2
Name: Parent code, dtype: int64

In [9]:
df.loc[(df['Parent code']==911),'Parent code']=910
df.loc[(df['Parent code']==913),'Parent code']=910
df.loc[(df['Parent code']==914),'Parent code']=910
df.loc[(df['Parent code']==912),'Parent code']=910

df.loc[(df['Parent code']==5501),'Parent code']=5500
df.loc[(df['Parent code']==906),'Parent code']=5500
df.loc[(df['Parent code']==902),'Parent code']=5500

df.loc[(df['Parent code']==916),'Parent code']=915
df.loc[(df['Parent code']==931),'Parent code']=915

df.loc[(df['Parent code']==954),'Parent code']=928
df.loc[(df['Parent code']==957),'Parent code']=928
df.loc[(df['Parent code']==922),'Parent code']=5500
df.loc[(df['Parent code']==920),'Parent code']=5500
df.loc[(df['Parent code']==924),'Parent code']=925
df.loc[(df['Parent code']==923),'Parent code']=925
df.loc[(df['Parent code']==926),'Parent code']=925

df.loc[(df['Parent code']==927),'Parent code']=928

df.loc[(df['Parent code']==918),'Parent code']=915

In [10]:
cols=['country_code','fert_1950_1955','fert_2015_2020','mort_1950_1955','mort_2015_2020','country_name','parent_code','pop_1950_1955','pop_2015_2020']

In [11]:
df.columns=cols

In [12]:
df

,country_code,fert_1950_1955,fert_2015_2020,mort_1950_1955,mort_2015_2020,country_name,parent_code,pop_1950_1955,pop_2015_2020
0,108,6.80,5.45,280,63,Burundi,910,2 403,11 012
1,174,6.00,4.24,288,70,Comoros,910,166,823
2,262,6.31,2.76,260,51,Djibouti,910,65,951
3,232,6.97,4.10,333,44,Eritrea,910,851,3 438
4,231,7.17,4.30,333,55,Ethiopia,910,18 832,107 851
...,...,...,...,...,...,...,...,...,...
196,442,1.98,1.45,56,4,Luxembourg,925,300,597
197,528,3.05,1.66,30,3,Netherlands,925,10 302,17 039
198,756,2.31,1.54,36,4,Switzerland,925,4 783,8 484
199,124,3.65,1.53,44,5,Canada,915,14 468,36 895
200,840,3.31,1.78,35,7,United States of America,915,163 518,326 024

In [13]:
df.loc[(df['parent_code']==910),'parent_code']='Africa'
df.loc[(df['parent_code']==915),'parent_code']='America'
df.loc[(df['parent_code']==5500),'parent_code']='Asia'
df.loc[(df['parent_code']==925),'parent_code']='Europe'
df.loc[(df['parent_code']==928),'parent_code']='Oceania'
df.loc[(df['country_code']==840),'parent_code']='US'
df.loc[(df['country_code']==156),'parent_code']='China'

In [14]:
df['parent_code'].value_counts()

Africa     57
Asia       50
Europe     40
America    39
Oceania    13
China       1
US          1
Name: parent_code, dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 0 to 200
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_code    201 non-null    int64
 1   fert_1950_1955  201 non-null    float64
 2   fert_2015_2020  201 non-null    float64
 3   mort_1950_1955  201 non-null    int64
 4   mort_2015_2020  201 non-null    int64
 5   country_name    201 non-null    object
 6   parent_code     201 non-null    object
 7   pop_1950_1955   201 non-null    object
 8   pop_2015_2020   201 non-null    object
dtypes: float64(2), int64(3), object(4)
memory usage: 15.7+ KB

In [16]:
df=df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 0 to 200
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_code    201 non-null    int64
 1   fert_1950_1955  201 non-null    float64
 2   fert_2015_2020  201 non-null    float64
 3   mort_1950_1955  201 non-null    int64
 4   mort_2015_2020  201 non-null    int64
 5   country_name    201 non-null    object
 6   parent_code     201 non-null    object
 7   pop_1950_1955   201 non-null    object
 8   pop_2015_2020   201 non-null    object
dtypes: float64(2), int64(3), object(4)
memory usage: 15.7+ KB

In [17]:
#df['purchase'].astype(str).astype(int)
#df2['employee_id'] = df2['employee_id'].str.strip()
df['pop_1950_1955']=df['pop_1950_1955'].str.replace(" ","")
df['pop_1950_1955']=df['pop_1950_1955'].astype(str).astype(int)
df['pop_2015_2020']=df['pop_2015_2020'].str.replace(" ","")
df['pop_2015_2020']=df['pop_2015_2020'].astype(str).astype(int)
df.head()

,country_code,fert_1950_1955,fert_2015_2020,mort_1950_1955,mort_2015_2020,country_name,parent_code,pop_1950_1955,pop_2015_2020
0,108,6.80,5.45,280,63,Burundi,Africa,2403,11012
1,174,6.00,4.24,288,70,Comoros,Africa,166,823
2,262,6.31,2.76,260,51,Djibouti,Africa,65,951
3,232,6.97,4.10,333,44,Eritrea,Africa,851,3438
4,231,7.17,4.30,333,55,Ethiopia,Africa,18832,107851

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 0 to 200
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_code    201 non-null    int64
 1   fert_1950_1955  201 non-null    float64
 2   fert_2015_2020  201 non-null    float64
 3   mort_1950_1955  201 non-null    int64
 4   mort_2015_2020  201 non-null    int64
 5   country_name    201 non-null    object
 6   parent_code     201 non-null    object
 7   pop_1950_1955   201 non-null    int64
 8   pop_2015_2020   201 non-null    int64
dtypes: float64(2), int64(5), object(2)
memory usage: 15.7+ KB

In [19]:
df2=df

In [20]:
df2=df2[df2['pop_1950_1955']>6000]
df2=df2[df2['pop_2015_2020']>10000]

In [21]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57 entries, 4 to 200
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country_code    57 non-null     int64
 1   fert_1950_1955  57 non-null     float64
 2   fert_2015_2020  57 non-null     float64
 3   mort_1950_1955  57 non-null     int64
 4   mort_2015_2020  57 non-null     int64
 5   country_name    57 non-null     object
 6   parent_code     57 non-null     object
 7   pop_1950_1955   57 non-null     int64
 8   pop_2015_2020   57 non-null     int64
dtypes: float64(2), int64(5), object(2)
memory usage: 4.5+ KB

In [22]:
df2['parent_code'].value_counts()

Asia       21
Europe     14
Africa     11
America     8
China       1
Oceania     1
US          1
Name: parent_code, dtype: int64

In [23]:
df2['fert_1950_1955'].value_counts()

6.35    2
6.75    2
7.17    1
2.85    1
5.40    1
4.15    1
3.15    1
6.10    1
4.85    1
6.51    1
6.95    1
3.18    1
2.74    1
3.63    1
3.06    1
2.81    1
7.42    1
2.18    1
2.48    1
2.36    1
3.10    1
2.53    1
2.37    1
2.76    1
2.13    1
3.05    1
3.65    1
6.14    1
5.49    1
6.00    1
7.48    1
6.34    1
6.74    1
5.98    1
6.05    1
7.28    1
6.61    1
6.65    1
7.30    1
6.69    1
4.41    1
5.30    1
7.45    1
6.36    1
5.90    1
6.91    1
5.96    1
6.60    1
5.80    1
6.11    1
6.72    1
3.46    1
2.96    1
5.65    1
3.31    1
Name: fert_1950_1955, dtype: int64

In [24]:
df2.head(57)

,country_code,fert_1950_1955,fert_2015_2020,mort_1950_1955,mort_2015_2020,country_name,parent_code,pop_1950_1955,pop_2015_2020
4,231,7.17,4.30,333,55,Ethiopia,Africa,18832,107851
5,404,7.48,3.52,248,47,Kenya,Africa,6424,50815
10,508,6.34,4.89,319,73,Mozambique,Africa,6170,29106
17,834,6.74,4.92,264,57,United Republic of Tanzania,Africa,8061,55541
25,180,5.98,5.96,281,100,Democratic Republic of the Congo,Africa,12692,82809
33,710,6.05,2.41,228,35,South Africa,Africa,14237,57377
46,566,6.35,5.42,335,102,Nigeria,Africa,39075,193491
50,12,7.28,3.05,278,25,Algeria,Africa,9201,41800
51,818,6.75,3.33,387,20,Egypt,Africa,21503,97413
53,504,6.61,2.42,252,23,Morocco,Africa,9552,35797
54,729,6.65,4.43,227,64,Sudan,Africa,6047,41338
62,368,7.30,3.68,327,28,Iraq,Asia,6052,37950
72,792,6.69,2.08,292,13,Turkey,Asia,22524,81597
75,398,4.41,2.76,144,10,Kazakhstan,Asia,7075,18188
79,860,5.30,2.43,156,26,Uzbekistan,Asia,6667,32210
80,4,7.45,4.56,405,68,Afghanistan,Asia,7944,36706
81,50,6.36,2.05,315,32,Bangladesh,Asia,39507,160505
83,356,5.90,2.24,271,39,India,Asia,389125,1345402
84,364,6.91,2.15,298,15,Iran (Islamic Republic of),Asia,17952,81240
86,524,5.96,1.93,334,34,Nepal,Asia,8828,27959
87,586,6.60,3.55,341,75,Pakistan,Asia,38586,210108
88,144,5.80,2.21,144,9,Sri Lanka,Asia,8269,21170
89,156,6.11,1.69,205,12,China,China,580665,1423779
92,158,6.72,1.15,110,5,"China, Taiwan Province of China",Asia,8245,23695
93,408,3.46,1.91,200,18,Dem. People's Republic of Korea,Asia,10155,25486
94,392,2.96,1.37,72,2,Japan,Asia,85526,127298
96,410,5.65,1.11,251,3,Republic of Korea,Asia,19928,51095
99,360,5.49,2.32,276,25,Indonesia,Asia,72395,266068
101,458,6.35,2.01,144,7,Malaysia,Asia,6461,31317
102,104,6.00,2.17,317,48,Myanmar,Asia,18456,53545
103,608,7.42,2.58,137,28,Philippines,Asia,19971,105883
105,764,6.14,1.53,189,9,Thailand,Asia,21862,69292
107,704,5.40,2.06,158,21,Viet Nam,Asia,26034,95044
112,192,4.15,1.62,113,6,Cuba,America,6175,11333
130,484,6.75,2.14,193,16,Mexico,America,29628,125445
133,32,3.15,2.27,84,12,Argentina,America,17742,44143
135,76,6.10,1.74,190,15,Brazil,America,57323,208591
136,152,4.85,1.65,159,8,Chile,America,6876,18574
137,170,6.51,1.82,167,15,Colombia,America,12656,49248
142,604,6.95,2.27,267,16,Peru,America,8193,31719
146,36,3.18,1.83,30,4,Australia,Oceania,8585,24730
161,203,2.74,1.64,50,3,Czechia,Europe,9103,10654
163,616,3.63,1.42,92,4,Poland,Europe,25779,37939
165,642,3.06,1.62,113,8,Romania,Europe,16753,19581
166,643,2.85,1.82,142,7,Russian Federation,Europe,106067,145555
168,804,2.81,1.44,113,9,Ukraine,Europe,38372,44349
179,826,2.18,1.75,33,4,United Kingdom,Europe,50702,66907
183,300,2.48,1.30,58,3,Greece,Europe,7811,10544
184,380,2.36,1.33,73,3,Italy,Europe,47358,60592
188,620,3.10,1.29,135,3,Portugal,Europe,8471,10277
191,724,2.53,1.33,82,3,Spain,Europe,28421,46690
193,56,2.37,1.71,51,3,Belgium,Europe,8732,11446
194,250,2.76,1.85,52,4,France,Europe,42372,64893
195,276,2.13,1.59,55,4,Germany,Europe,70610,82844
197,528,3.05,1.66,30,3,Netherlands,Europe,10302,17039
199,124,3.65,1.53,44,5,Canada,America,14468,36895
200,840,3.31,1.78,35,7,United States of America,US,163518,326024

In [25]:
df2.to_csv('dv_fp.csv', index=False)

In [26]:
df2['fert_1950_1955'].mean()

5.095263157894738

In [27]:
df2['fert_2015_2020'].mean()

2.361228070175438